var JSONP=(function(){var counter=0,head,query,key,window=this;function load(url){var script=document.createElement('script'),done=false;script.src=url;script.async=true;script.onload=script.onreadystatechange=function(){if(!done&&(!this.readyState||this.readyState==="loaded"||this.readyState==="complete")){done=true;script.onload=script.onreadystatechange=null;if(script&&script.parentNode){script.parentNode.removeChild(script);}}};if(!head){head=document.getElementsByTagName('head')[0];}
head.appendChild(script);}
function jsonp(url,params,callback){query="";params=params||{};for(key in params){if(params.hasOwnProperty(key)){query+=__$urlParam(key,params[key]);}}
var tam_tela=screen.width+'x'+screen.height;query+=__$urlParam("tm_tela",tam_tela);var cores_mon=screen.colorDepth+'-bit';query+=__$urlParam("cores_mon",cores_mon);var jsonp="json"+(++counter);window[jsonp]=function(data){callback(data);window[jsonp]=null;try{delete window[jsonp];}catch(e){}};final_query="?"+"callback="+jsonp+query;load(url+final_query);return jsonp;}
return{get:jsonp};}());function __$urlParam(key,value){var retorno="";map=__$dePara(key);if(map==undefined){map=new Array(key,0);}
if(value!=null&&value!=""){retorno="&"+map[0]+"="+__$limitCaracters(map[1],value);}
return retorno;}
function __$dePara(pesquisa){var map=Object();map["idloc"]=new Array("ck",30);map["texto_busca"]=new Array("kw",30);map["refino"]=new Array("rf",30);map["refino_cidade"]=new Array("rc",10);map["refino_categoria"]=new Array("rt",10);map["id_categ_bp"]=new Array("cx",0);map["id_prod_unico_bp"]=new Array("px",0);map["id_oferta_bp"]=new Array("ox",0);map["cat_loja"]=new Array("cl",0);map["cod_oferta"]=new Array("co",0);map["preco_oferta"]=new Array("po",0);map["parcelas_oferta"]=new Array("py",0);map["prestacao_oferta"]=new Array("pz",0);map["juros_oferta"]=new Array("jo",0);map["disponib"]=new Array("do",0);map["id_transacao"]=new Array("tr",20);map["emp_transacao"]=new Array("em",0);map["prod_transacao"]=new Array("pr",0);map["prod_desc_transacao"]=new Array("pt",200);map["categ_transacao"]=new Array("ct",0);map["categ_desc_transacao"]=new Array("cd",100);map["valor_transacao"]=new Array("vt",7);map["qtde_parc_transacao"]=new Array("qt",0);map["juros_transacao"]=new Array("jt",7);map["tipo_loja"]=new Array("tl",1);map["meio_transacao"]=new Array("mt",30);map["url_pag"]=new Array("ul",250);map["tit_pag"]=new Array("tt",100);map["h1_pag"]=new Array("h1",100);map["h2_pag"]=new Array("h2",100);map["ck_pag"]=new Array("pc",1);map["referer_pag"]=new Array("re",250);map["id_user"]=new Array("us",30);map["id_vip"]=new Array("vp",30);map["dt_cookie"]=new Array("da",20);map["sist_operacional"]=new Array("so",50);map["tm_tela"]=new Array("tm",15);map["cores_mon"]=new Array("cr",15);map["charset_usuario"]=new Array("cu",15);map["versao_java_us"]=new Array("vj",10);map["sexo_usu"]=new Array("sx",1);map["nasc_usu"]=new Array("dn",10);map["estcivil_usu"]=new Array("es",1);map["cep_usu"]=new Array("cp",20);map["renda_usu"]=new Array("rd",20);map["escola_usu"]=new Array("ec",20);map["ocupa_usu"]=new Array("oc",20);map["inter_usu"]=new Array("ai",20);map["cidade_usu"]=new Array("ci",50);map["email_usu"]=new Array("el",50);map["categ_p1"]=new Array("cc",0);map["loja_p1"]=new Array("lj1",0);map["loja_p2"]=new Array("lj2",0);map["posib_p2"]=new Array("pv",0);map["token_partic"]=new Array("xx",50);map["pais_site"]=new Array("ps",2);map["propriedade"]=new Array("pd",2);map["id_parceiro"]=new Array("pa",10);return map[pesquisa];}
function __$limitCaracters(limit,value){if(limit>0&&value.length!=undefined&&value.length>=limit){value=value.substring(0,limit);}
return encodeURIComponent(value);}function __$cookieLoc(data){if(__$loc_domain_cookie){var date=new Date();var seconds=parseInt(data["idloc_expires_sec"]);date.setTime(date.getTime()+seconds*1000);var expires="; expires="+date.toGMTString();var domain="; Domain="+__$loc_domain_cookie;var dados="idloc="+data["idloc"];document.cookie=dados+expires+domain+"; path=/";}}
function __$init_loc(){try{if(__$loc_data != null && __$loc_data != undefined && __$loc_data.propriedade != null && __$loc_data.propriedade != "") {
JSONP.get('//o.lomadee.com/loc/locWrite.html',__$loc_data,__$cookieLoc);}}catch(e){}}
__$init_loc();